Repository Att-ies/frontend, pull requests merged in 2022-12, with the labels that each got.

#1 PR 템플릿 추가
  .github/pull_request_template.md
Labels: enhancement

#2 issue 템플릿 추가
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#6 로그인, 회원가입 Input 컴포넌트 생성
  src/components/common/Input/LoginInput.tsx
  src/components/common/Input/SignInInput.tsx
Labels: enhancement

#11 input 컴포넌트 디자인 수정
  src/components/common/Input.tsx
  src/components/common/Input/LoginInput.tsx
  src/components/common/Input/SignInInput.tsx
Labels: fix

#12 버튼 radius 수정
  src/components/common/button.tsx
Labels: fix

#13 tailwind config 설정
  src/components/common/layout.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: enhancement

#15 공통 컴포넌트 - Navigate Component
  src/assets/icons/icon_back.svg
  src/assets/icons/icon_close.svg
  src/components/common/Navigate.tsx
Labels: enhancement

#17 Modal component 추가
  src/components/common/Modal.tsx
Labels: enhancement

#20 회원가입 - 유저 페이지 퍼블리싱
  src/components/common/Layout.tsx
  src/components/common/Navigate.tsx
  src/pages/auth/user/join01.tsx
  src/pages/auth/user/join02.tsx
Labels: enhancement

#24 비밀번호 찾기 페이지 구현
  src/components/common/Modal.tsx
  src/pages/auth/password.tsx
  src/pages/auth/password/index.tsx
Labels: enhancement

#26 tsconfig 수정 ; "noImplicitAny": false, 추가
  tsconfig.json
Labels: bug

#27 2번 공통 회원가입 페이지 생성 & 에러메시지 컴포넌트 생성
  src/components/common/ErrorMessage.tsx
  src/pages/auth/join01.tsx
  src/pages/auth/join02.tsx
Labels: enhancement

#25 아이디 찾기 페이지 구현
  src/components/common/Navigate.tsx
  src/pages/auth/id.tsx
Labels: enhancement

#28 회원가입 시작 일반유저/작가 선택 페이지
  public/svg/icons/icon_author.svg
  public/svg/icons/icon_user.svg
  src/components/common/Layout.tsx
  src/components/common/Navigate.tsx
  src/pages/_app.tsx
  src/pages/auth/join.tsx
  src/pages/auth/join01.tsx
Labels: enhancement

#34 아이디 찾기 - 유효성 검사 추가
  src/pages/auth/id.tsx
Labels: fix

#35 검색 페이지 생성
  public/svg/icons/icon_grayClose.svg
  public/svg/icons/icon_home.svg
  src/pages/search.tsx
Labels: enhancement

#36 비밀번호 찾기 페이지 유효성 검사 추가
  src/pages/auth/password.tsx
Labels: fix

#37 index.tsx 추가
  src/pages/index.tsx
Labels: fix

#39 공통 회원가입01 페이지 체크박스 필수체크
  src/components/common/Button.tsx
  src/pages/auth/join01.tsx
Labels: fix

#40 유저 취햔분석 페이지 1,2 전역상태 관리
  src/pages/auth/user/join01.tsx
  src/pages/auth/user/join02.tsx
Labels: enhancement

#41 Chat main 페이지 구현
  public/svg/icons/icon_chat_main.svg
  src/pages/chat/[id].tsx
  src/pages/chat/index.tsx
Labels: enhancement

#42 버튼 컴포넌트 수정
  src/components/common/Button.tsx
  src/pages/auth/join01.tsx
Labels: fix

#44 채팅방, 채팅 메세지 컴포넌트 구현
  .yarn/cache/@types-react-npm-18.0.26-d708995a34-b62f0ea3cd.zip
  public/svg/icons/icon_back_white.svg
  public/svg/icons/icon_glasses.svg
  public/svg/icons/icon_option.svg
  public/svg/icons/icon_picture.svg
  src/components/common/ChattingMessage.tsx
  src/pages/chat/[id].tsx
Labels: enhancement

#45 react query 및 api 사용예시
  src/apis/README.md
  src/apis/_axios/instance.ts
  src/apis/example/exampleApi.mutaton.ts
  src/apis/example/exampleApi.query.ts
  src/apis/example/exampleApi.ts
  src/apis/example/exampleApi.type.ts
  src/apis/type.d.ts
  src/pages/_app.tsx
Labels: enhancement

#46 채팅 메인 페이지(index.js) 퍼블리싱
  public/svg/icons/icon_basic_profile.svg
  src/components/chat/ChatRoom.tsx
  src/components/common/Tab.tsx
  src/pages/chat/index.tsx
Labels: enhancement

#48 찜 목록 페이지 퍼블리싱 및 Navigate props 추가
  public/svg/icons/icon_favorite.svg
  src/components/common/Navigate.tsx
  src/components/wish/WishCard.tsx
  src/pages/profile/wish.tsx
Labels: enhancement

#49 프로필 페이지 제작 & mypage 컴포넌트 분리 & Navigate 공통 컴포넌트 수정
  public/svg/icons/icon_archive.svg
  public/svg/icons/icon_book.svg
  public/svg/icons/icon_dollar.svg
  public/svg/icons/icon_notification.svg
  public/svg/icons/icon_setting.svg
  src/components/common/Navigate.tsx
  src/components/mypage/Activity.tsx
  src/components/mypage/SettingItem.tsx
  src/components/mypage/TasteAnalyze.tsx
  src/pages/profile/index.tsx
Labels: enhancement

#47 프로필 수정 페이지 구현
  src/components/common/Input.tsx
  src/pages/chat/[id].tsx
  src/pages/profile/edit.tsx
Labels: enhancement

#51 Navigate 컴포넌트 수정 & profile edit 페이지 수정
  src/components/common/Navigate.tsx
  src/pages/profile/edit.tsx
Labels: enhancement

#50 개인 보완 페이지 퍼블리싱
  public/svg/icons/Tab/icon_auction.svg
  src/components/common/Modal.tsx
  src/pages/profile/password.tsx
  src/pages/profile/security.tsx
Labels: enhancement

#53 비밀번호 변경 페이지 퍼블리싱
  public/svg/icons/icon_eye.svg
  public/svg/icons/icon_eye_on.svg
  src/pages/profile/password.tsx
Labels: enhancement

#54 Chat방 디자인 반영
  public/svg/icons/icon_send.svg
  src/components/common/Modal.tsx
  src/components/common/Navigate.tsx
  src/pages/chat/[id].tsx
Labels: enhancement

#57 로그인 & 아이디 찾기 & 비밀번호 찾기 페이지 수정사항 반영
  src/components/common/Checkbox.tsx
  src/components/common/Modal.tsx
  src/pages/auth/id.tsx
  src/pages/auth/login.tsx
  src/pages/auth/password.tsx
Labels: fix

#55 알림 페이지 제작
  public/svg/icons/icon_lamp.svg
  src/components/notice/NoticeItem.tsx
  src/pages/notice.tsx
Labels: enhancement

#56 나의 픽작가 작가소개/작품 탭 퍼블리싱
  .yarn/cache/@headlessui-tailwindcss-npm-0.1.2-6482d9281e-3499f69eee.zip
  package.json
  public/svg/icons/icon_behance_black.svg
  public/svg/icons/icon_behance_gray.svg
  public/svg/icons/icon_instagram_black.svg
  public/svg/icons/icon_instagram_gray.svg
  src/components/profile/pick/PickArtist.tsx
  src/components/profile/pick/PickArtistWork.tsx
  src/pages/auth/artist/join02.tsx
  src/pages/profile/index.tsx
  src/pages/profile/pick/[id].tsx
  tailwind.config.js
  yarn.lock
Labels: enhancement
