Repository Att-ies/frontend, pull requests merged in 2023-01, with the labels that each got.

#58 auth/user/join페이지 리팩토링
  src/components/common/Input.tsx
  src/components/common/Modal.tsx
  src/pages/auth/join02.tsx
  src/pages/auth/user/join01.tsx
  src/pages/auth/user/join02.tsx
Labels: enhancement

#60 rtk 필드 변수명 수정 & 공통 회원가입 2번 페이지 폼 변수명 수정
  src/features/user/userSlice.ts
  src/pages/auth/join02.tsx
Labels: fix

#61 join02 페이지 폼 필드 재수정
  src/pages/auth/join02.tsx
Labels: fix

#62 로그인 페이지 리펙토링
  src/components/common/Checkbox.tsx
  src/pages/auth/id.tsx
  src/pages/auth/join01.tsx
  src/pages/auth/login.tsx
Labels: enhancement

#64 회원가입 - artist리펙토링
  src/components/common/Button.tsx
  src/features/user/userSlice.ts
  src/pages/auth/artist/join02.tsx
  src/pages/auth/join01.tsx
  src/pages/auth/join02.tsx
  src/pages/auth/user/join02.tsx
Labels: enhancement

#66 Aritst 회원가입 페이지 formData추가
  src/pages/auth/artist/join02.tsx
Labels: enhancement

#67 로컬 회원가입 구현
  src/apis/auth/authApi.ts
  src/apis/auth/authApi.type.ts
  src/components/common/DoubleCheckButton.tsx
  src/components/common/Input.tsx
  src/pages/auth/join02.tsx
Labels: enhancement

#68 검색 페이지 리펙토링
  src/pages/search.tsx
Labels: enhancement

#69 알림 페이지 리펙토링
  src/components/notice/NoticeItem.tsx
  src/pages/notice.tsx
  tailwind.config.js
Labels: enhancement

#71 ChatRoom페이지 리펙토링
  src/components/chat/ChatMessage.tsx
  src/components/chat/ChatRoom.tsx
  src/components/chat/ChattingMessage.tsx
  src/pages/chat/[id].tsx
  src/pages/chat/index.tsx
Labels: enhancement

#72 알림 페이지 컴포넌트 타입 수정
  src/components/notice/NoticeItem.tsx
Labels: fix

#73 프로필 페이지(~비밀번호 변경) 리펙토링
  public/svg/icons/icon_heart.svg
  src/components/mypage/SettingItem.tsx
  src/components/profile/pick/PickArtist.tsx
  src/components/profile/pick/PickArtistWork.tsx
  src/components/profile/wish/WishCard.tsx
  src/pages/profile/history.tsx
  src/pages/profile/index.tsx
  src/pages/profile/logout.tsx
  src/pages/profile/pick/[id].tsx
  src/pages/profile/pick/index.tsx
  src/pages/profile/security/index.tsx
  src/pages/profile/security/password.tsx
  src/pages/profile/wish.tsx
  src/pages/search.tsx
Labels: enhancement, fix

#75 프로필 수정 페이지 구현
  src/pages/profile/edit.tsx
Labels: enhancement

#74 경매 페이지 구현
  public/svg/icons/Tab/icon_auction_focus.svg
  public/svg/icons/icon_arrow_sort.svg
  public/svg/icons/icon_logo.svg
  public/svg/icons/icon_search.svg
  src/components/auction/AuctionNavigate.tsx
  src/pages/auction/index.tsx
Labels: bug, enhancement

#80 작가 회원가입 구현 & slice수정
  src/apis/auth/authApi.ts
  src/components/common/Checkbox.tsx
  src/features/user/userSlice.ts
  src/pages/auth/artist/join02.tsx
Labels: enhancement, fix

#81 일반 회원가입 API구현 & types 폴더 추가
  src/apis/auth/authApi.ts
  src/components/common/ErrorMessage.tsx
  src/features/user/userSlice.ts
  src/mocks/handlers.ts
  src/pages/auth/join02.tsx
  src/pages/auth/user/join01.tsx
  src/pages/auth/user/join02.tsx
  src/pages/index.tsx
  src/types/userInfo.ts
Labels: enhancement

#82 작가 회원가입 response 핸들링
  src/apis/auth/authApi.ts
  src/pages/auth/artist/join02.tsx
Labels: fix

#86 문의 페이지 구현
  public/svg/icons/icon_arrow_down.svg
  src/pages/inquiry.tsx
Labels: enhancement

#84 React Query 이용하여 일반 회원가입 API 구현
  src/apis/_axios/authInstance.ts
  src/apis/auth/authApi.ts
  src/hooks/queries/useUserJoin.ts
  src/pages/_app.tsx
  src/pages/auth/user/join01.tsx
  src/pages/auth/user/join02.tsx
  src/pages/index.tsx
Labels: enhancement

#88 일반회원가입 - 취향분석 키워드 추가
  src/pages/auth/user/join02.tsx
Labels: enhancement

#90 중복체크 에러핸들링
  src/apis/auth/authApi.ts
  src/pages/auth/join02.tsx
Labels: enhancement

#92 회원가입 라우팅 변경
  src/apis/auth/authApi.ts
  src/pages/auth/artist/join01.tsx
  src/pages/auth/artist/join02.tsx
  src/pages/auth/join.tsx
  src/pages/auth/join01.tsx
  src/pages/auth/join02.tsx
  src/pages/auth/join03.tsx
  src/pages/auth/join04.tsx
  src/pages/auth/login.tsx
Labels: enhancement

#93 프로필 페이지 구현
  public/svg/icons/icon_arrow_black.svg
  public/svg/icons/icon_arrow_light_gray.svg
  public/svg/icons/icon_plus_pink.svg
  public/svg/icons/icon_user_gray.svg
  src/components/mypage/Activity.tsx
  src/components/mypage/SettingItem.tsx
  src/components/mypage/TasteAnalyze.tsx
  src/components/profile/ArtItem.tsx
  src/components/profile/wish/WishCard.tsx
  src/pages/profile/index.tsx
Labels: enhancement, fix

#94 닉네임 중복체크 추가 + 중복체크 함수 통일
  src/apis/auth/authApi.ts
  src/pages/auth/join02.tsx
Labels: enhancement

#95 로그인 페이지의 중복 코드 제거
  src/pages/auth/login.tsx
Labels: enhancement

#96 header token 담는 방식 변경 및 isUser utill 함수
  src/apis/_axios/instance.ts
  src/apis/auth/authApi.ts
  src/pages/profile/edit.tsx
  src/types/user.ts
  src/utils/isUser.ts
Labels: fix

#97 회원탈퇴 구현
  src/apis/_axios/instance.ts
  src/apis/auth/authApi.ts
  src/pages/profile/index.tsx
  src/pages/profile/security/index.tsx
Labels: enhancement, fix

#98 프로필 페이지 getProfile(members.me)
  src/apis/auth/authApi.ts
  src/pages/profile/index.tsx
Labels: enhancement

#99 비밀번호 변경 API
  src/apis/_axios/authInstance.ts
  src/apis/auth/authApi.ts
  src/pages/profile/index.tsx
  src/pages/profile/security/password.tsx
Labels: enhancement

#102 프로필 페이지
  public/svg/icons/icon_pencil.svg
  public/svg/icons/icon_pencil_black.svg
  src/apis/_axios/instance.ts
  src/apis/auth/authApi.ts
  src/components/mypage/SettingItem.tsx
  src/pages/profile/index.tsx
Labels: enhancement

#103 1:1 문의 페이지 파일업로드 구현
  public/svg/icons/icon_camera_black.svg
  public/svg/icons/icon_close_white.svg
  src/components/inquiry/FileItem.tsx
  src/pages/inquiry.tsx
Labels: enhancement, fix

#106 수정 페이지 중복체크 추가, API구현 & authAPI 통일화
  src/apis/auth/authApi.ts
  src/pages/auth/join04.tsx
  src/pages/profile/edit.tsx
Labels: enhancement

#109 스크롤바 생성 & 감추기 & detail페이지 구현 & 프로필 수정 API 구현
  public/static/favicon.ico
  public/svg/example/detail.svg
  public/svg/example/guarantee.svg
  public/svg/icons/icon_document_upload.svg
  public/svg/icons/icon_speaker.svg
  public/svg/icons/icon_trash_can.svg
  src/apis/auth/authApi.ts
  src/apis/auth/authApi.type.ts
  src/components/common/Layout.tsx
  src/components/profile/pick/PickArtistWork.tsx
  src/pages/_app.tsx
  src/pages/detail.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/pick/[id].tsx
  src/pages/profile/register.tsx
  tailwind.config.js
Labels: enhancement

#110 profile register(작가로 전환) 페이지 퍼블리싱
  public/static/favicon.ico
  public/svg/example/detail.svg
  public/svg/example/guarantee.svg
  public/svg/icons/icon_document_upload.svg
  public/svg/icons/icon_speaker.svg
  public/svg/icons/icon_trash_can.svg
  src/apis/auth/authApi.ts
  src/apis/auth/authApi.type.ts
  src/components/common/Layout.tsx
  src/components/profile/pick/PickArtistWork.tsx
  src/pages/_app.tsx
  src/pages/detail.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/pick/[id].tsx
  src/pages/profile/register.tsx
  tailwind.config.js
Labels: enhancement

#112 register completed 페이지 퍼블리싱
  src/apis/auth/authApi.ts
  src/components/common/Navigate.tsx
  src/components/common/Tab.tsx
  src/pages/index.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/register/complete.tsx
  src/pages/profile/register/index.tsx
Labels: enhancement

#113 리펙토링 & edit페이지 string예외처리
  src/apis/auth/authApi.ts
  src/components/common/Navigate.tsx
  src/components/common/Tab.tsx
  src/pages/index.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/register/complete.tsx
  src/pages/profile/register/index.tsx
Labels: enhancement

#114 문의 페이지 파일 업로드 수정
  public/svg/icons/icon_logo_brand.svg
  public/svg/icons/icon_search_white.svg
  src/components/inquiry/FileItem.tsx
  src/components/inquiry/InquiryItem.tsx
  src/pages/inquiry.tsx
Labels: enhancement, fix

#115 profile hook 만들고 적용
  src/apis/_axios/instance.ts
  src/apis/auth/authApi.ts
  src/hooks/queries/useGetProfile.ts
  src/mocks/server.ts
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/utils/makeBlob.ts
Labels: Feature

#116 프로필 수정 페이지 보완
  src/apis/auth/authApi.ts
  src/hooks/queries/useDuplicateCheck.ts
  src/pages/profile/edit.tsx
Labels: Feature

#126 feat : 아이디 저장 기능 추가
  src/pages/auth/login.tsx
  src/utils/localStorage/token/index.ts
Labels: Feature

#127 전자 서명 구현
  .yarn/cache/@types-react-signature-canvas-npm-1.0.2-edb9637260-cf7dff4004.zip
  .yarn/cache/@types-signature_pad-npm-2.3.2-2c623f64e9-dab6dd7409.zip
  .yarn/cache/react-signature-canvas-npm-1.0.6-fcb9870592-4fe5f0c411.zip
  .yarn/cache/signature_pad-npm-2.3.2-7d69e272f0-f64fdc0a27.zip
  .yarn/cache/trim-canvas-npm-0.1.2-ddd6cb5761-0068b721fc.zip
  package.json
  public/svg/example/guarantee_empty.svg
  public/svg/icons/icon_reset.svg
  src/components/common/Navigate.tsx
  src/features/signature/signatureSlice.ts
  src/features/store.ts
  src/pages/exhibition/post/guarantee.tsx
  src/pages/exhibition/post/index.tsx
  yarn.lock
Labels: Feature

#128 경매 페이지 구현
  public/svg/icons/icon_clock.svg
  src/components/auction/ArtWorkItem.tsx
  src/components/auction/AuctionNavigate.tsx
  src/components/common/Navigate.tsx
  src/components/common/Tab.tsx
  src/components/profile/pick/PickArtist.tsx
  src/pages/auction/index.tsx
Labels: Feature

#129 경매 상세페이지 구현
  public/svg/icons/icon_clock_black.svg
  src/components/common/DivisionBar.tsx
  src/pages/auction/detail.tsx
Labels: Feature

#135 전시회 페이지 구현
  public/svg/example/exhibition.svg
  public/svg/icons/bg_canvas.svg
  public/svg/icons/bg_exhibition.jpg
  public/svg/icons/icon_arrow_white.svg
  public/svg/icons/icon_maximize.svg
  public/svg/icons/icon_swipe_arrow.svg
  src/components/exhibition/Modal.tsx
  src/pages/exhibition/index.tsx
Labels: Feature

#131 작가로 변환 API 구현
  src/apis/auth/authApi.ts
  src/pages/profile/register/index.tsx
Labels: Feature

#136 구매 작품 페이지 구현
  public/svg/example/example_picture_col.svg
  src/components/profile/AuctionArtItem.tsx
  src/pages/auth/login.tsx
  src/pages/profile/buying.tsx
  src/pages/profile/index.tsx
Labels: Feature

#144 작가서명 전역변수 작제 및 작품등록 구현 중
  src/components/common/Input.tsx
  src/components/common/Select.tsx
  src/components/common/Selectkeyword.tsx
  src/components/home/guarantee.tsx
  src/features/signature/signatureSlice.ts
  src/features/store.ts
  src/pages/home/post/index.tsx
  src/types/artwork.ts
Labels: Feature

#148 취향분석 페이지 디자인 반영
  public/svg/example/example_keyword.svg
  src/components/common/Selectkeyword.tsx
  src/pages/auth/join03.tsx
Labels: Feature

#146 시작(begin)페이지 구현
  public/svg/begin/begin_01.svg
  public/svg/begin/begin_02.svg
  public/svg/begin/begin_03.svg
  src/pages/auth/login.tsx
  src/pages/begin.tsx
Labels: Feature

#151 프로필 수정 페이지 isChanged(사진 변경/안변경) 적용
  src/pages/profile/edit.tsx
Labels: Feature

#156 비밀번호 변경 -> 409 에러핸들링
  src/apis/auth/authApi.ts
  src/pages/profile/security/password.tsx
Labels: fix

#153 select 컴포넌트 수정 및 작품등록에 3가지 모달 적용
  public/svg/icons/icon_arrow_down_black.svg
  src/components/common/Select.tsx
  src/components/home/post/GenreModal.tsx
  src/components/home/post/GenreSelect.tsx
  src/components/home/post/GuaranteeModal.tsx
  src/components/home/post/KeywordModal.tsx.tsx
  src/components/home/post/KeywordSelect.tsx
  src/pages/home/post/index.tsx
Labels: Feature

#154 리펙토링
  src/apis/auth/authApi.ts
  src/hooks/queries/useGetProfile.ts
  src/hooks/queries/useUserJoin.ts
  src/hooks/useTimer.tsx
  src/pages/_app.tsx
  src/pages/profile/index.tsx
  src/pages/profile/inquiry.tsx
Labels: fix

#163 전시회 페이지 그림확대시 배경 크기 수정 & swiper navigation 버튼 구현
  src/components/exhibition/Modal.tsx
  src/pages/exhibition/index.tsx
Labels: Feature, fix

#160 작가 픽 목록, 픽 상세 조회 API 구현
  src/components/profile/pick/PickArtist.tsx
  src/hooks/queries/useGetPick.ts
  src/hooks/queries/useGetPickDetail.ts
  src/pages/profile/pick/[id].tsx
  src/pages/profile/pick/index.tsx
Labels: Feature

#164 리팩토링 & 타입 오류 해결 (회원가입)
  public/svg/icons/Tab/icon_home_focus.svg
  src/apis/_axios/instance.ts
  src/apis/auth/authApi.ts
  src/components/common/DoubleCheckButton.tsx
  src/components/common/Layout.tsx
  src/components/home/AuctionItem.tsx
  src/components/inquiry/FileItem.tsx
  src/components/inquiry/InquiryItem.tsx
  src/components/mypage/Activity.tsx
  src/components/mypage/SettingItem.tsx
  src/components/profile/pick/PickArtist.tsx
  src/hooks/queries/useUserJoin.ts
  src/pages/auth/artist/join01.tsx
  src/pages/auth/artist/join02.tsx
  src/pages/auth/id.tsx
  src/pages/auth/join.tsx
  src/pages/auth/join02.tsx
  src/pages/auth/join04.tsx
  src/pages/chat/index.tsx
  src/pages/detail.tsx
  src/pages/home/index.tsx
  src/pages/profile/index.tsx
  src/pages/profile/inquiry.tsx
Labels: BugFix

#165 작가등록 구현
  src/apis/artwork/artworkApi.ts
  src/apis/artwork/artworkApi.type.ts
  src/components/common/Input.tsx
  src/components/home/post/GuaranteeModal.tsx
  src/components/home/post/KeywordSelect.tsx
  src/pages/home/post/index.tsx
Labels: Feature

#169 @types 폴더 에서 전역 type 정의 및 픽작가 리팩토링
  src/@types/index.d.ts
  src/apis/_axios/instance.ts
  src/components/profile/pick/PickArtist.tsx
  src/features/user/userSlice.ts
  src/hooks/queries/useGetPick.ts
  src/hooks/queries/useGetPickDetail.ts
  src/hooks/queries/useGetProfile.ts
  src/hooks/queries/useUserJoin.ts
  src/pages/auth/kakao/callback.tsx
  src/pages/auth/naver/callback.tsx
  src/pages/profile/pick/[id].tsx
  src/pages/profile/pick/index.tsx
  src/pages/profile/register/index.tsx
  src/types/artwork.ts
  src/types/user.ts
  src/utils/localStorage/token/index.ts
  tsconfig.json
Labels: config

#170 Feature/type error etc
  src/pages/auction/index.tsx
  src/pages/begin.tsx
  src/pages/index.tsx
  src/pages/search.tsx
Labels: BugFix

#171 auth 타입 에러 수정 및 리팩토링
  src/apis/auth/authApi.ts
  src/components/common/Modal.tsx
  src/pages/auth/join02.tsx
  src/pages/auth/join03.tsx
  src/pages/auth/join04.tsx
  src/pages/auth/login.tsx
  src/pages/auth/password.tsx
Labels: fix

#174 import beautify 적용 & 리팩토링 진행
  public/svg/begin/begin_03.svg
  src/apis/_axios/instance.ts
  src/apis/artwork/artworkApi.ts
  src/apis/artwork/artworkApi.type.ts
  src/apis/auth/authApi.ts
  src/apis/auth/authApi.type.ts
  src/apis/chat/chatApi.ts
  src/components/auction/ArtWorkItem.tsx
  src/components/auction/AuctionNavigate.tsx
  src/components/chat/ChatRoom.tsx
  src/components/common/Button.tsx
  src/components/common/Checkbox.tsx
  src/components/common/DivisionBar.tsx
  src/components/common/DoubleCheckButton.tsx
  src/components/common/Input.tsx
  src/components/common/Layout.tsx
  src/components/common/Modal.tsx
  src/components/common/Navigate.tsx
  src/components/common/Select.tsx
  src/components/common/Selectkeyword.tsx
  src/components/common/Tab.tsx
  src/components/exhibition/Modal.tsx
  src/components/home/AuctionItem.tsx
  src/components/home/Calendar.tsx
  src/components/home/ExhibitionItem.tsx
  src/components/home/ScheduleItem.tsx
  src/components/home/post/GenreModal.tsx
  src/components/home/post/GenreSelect.tsx
  src/components/home/post/GuaranteeModal.tsx
  src/components/home/post/KeywordModal.tsx.tsx
  src/components/home/post/KeywordSelect.tsx
  src/components/inquiry/FileItem.tsx
  src/components/mypage/SettingItem.tsx
  src/features/hooks.ts
  src/features/store.ts
  src/features/user/userSlice.ts
  src/hooks/queries/useDuplicateCheck.ts
  src/hooks/queries/useGetPick.ts
  src/hooks/queries/useGetPickDetail.ts
  src/hooks/queries/useGetProfile.ts
  src/hooks/queries/useUserJoin.ts
  src/pages/_app.tsx
  src/pages/api/hello.ts
  src/pages/auction/detail.tsx
  src/pages/auction/index.tsx
  src/pages/begin.tsx
  src/pages/chat/[id].tsx
  src/pages/chat/index.tsx
  src/pages/detail.tsx
  src/pages/exhibition/index.tsx
  src/pages/home/index.tsx
  src/pages/home/post/index.tsx
  src/pages/index.tsx
  src/pages/notice.tsx
  src/pages/search.tsx
  src/stories/Button.stories.tsx
  src/stories/Button.tsx
  src/utils/isUser.ts
  src/utils/localStorage/token/index.ts
  src/utils/makeBlob.ts
Labels: BugFix

#175 컴포넌트 타입 수정 & 유틸 함수 생성
  src/components/inquiry/InquiryItem.tsx
  src/components/login/SocialLoginButton.tsx
  src/components/mypage/Activity.tsx
  src/components/notice/NoticeItem.tsx
  src/components/profile/AuctionArtItem.tsx
  src/components/profile/pick/PickArtist.tsx
  src/pages/auth/id.tsx
  src/pages/auth/join01.tsx
  src/pages/auth/join02.tsx
  src/pages/auth/join03.tsx
  src/pages/auth/join04.tsx
  src/pages/auth/login.tsx
  src/pages/auth/password.tsx
  src/utils/randomString.ts
Labels: fix

#182 instace 수정 & API 구현(판매 페이지 API, 작가 정보 수정 API, 취향 변경 API)
  src/apis/_axios/instance.ts
  src/apis/artwork/artworkApi.ts
  src/apis/auth/authApi.ts
  src/hooks/queries/useGetSellingArtWork.ts
  src/pages/home/post.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/keyword.tsx
  src/pages/profile/selling.tsx
Labels: Feature

#185 취향 맞춤 작품 API/훅 구현 & 디자인 수정 & home/view퍼블리싱
  public/svg/icons/Tab/icon_exhibition.svg
  src/apis/_axios/instance.ts
  src/components/home/AuctionItem.tsx
  src/hooks/queries/useGetKeywordArtWork.ts
  src/pages/auth/login.tsx
  src/pages/begin.tsx
  src/pages/home/history.tsx
  src/pages/home/index.tsx
  src/pages/home/view.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/keyword.tsx
Labels: Feature

#187 달력 시작요일 월요일 수정
  src/components/home/Calendar.tsx
Labels: fix

#190 brand 칼라 적용 & tailwindcss - prettier(자동 정렬) 모듈 추가
  .eslintrc.js
  .prettierrc.js
  .yarn/cache/prettier-plugin-tailwindcss-npm-0.2.1-848c29a572-5a04b26f50.zip
  next.config.js
  package.json
  public/svg/icons/Tab/icon_exhibition.svg
  src/components/common/Button.tsx
  src/components/common/Loader.tsx
  src/components/home/Calendar.tsx
  src/components/home/post/GenreSelect.tsx
  src/components/home/post/KeywordSelect.tsx
  src/components/inquiry/InquiryItem.tsx
  src/components/login/SocialLoginButton.tsx
  src/components/profile/Selectkeyword.tsx
  src/hooks/queries/useGetKeywordArtWork.ts
  src/pages/auth/id.tsx
  src/pages/auth/join02.tsx
  src/pages/auth/join03.tsx
  src/pages/auth/password.tsx
  src/pages/begin.tsx
  src/pages/detail.tsx
  src/pages/home/post.tsx
  src/pages/profile/buying.tsx
  src/pages/profile/index.tsx
  src/pages/profile/inquiry.tsx
  src/pages/profile/keyword.tsx
  src/pages/profile/selling.tsx
  src/pages/search.tsx
  src/stories/Button.tsx
  src/stories/REDAME.md
  tailwind.config.js
  yarn.lock
Labels: Feature

#193 Feature/edit instance
  .yarn/cache/tailwindcss-npm-3.2.1-05b070dd97-8479f6e469.zip
  .yarn/cache/tailwindcss-npm-3.2.4-5ba810eab4-ec187d180c.zip
  package.json
  src/apis/_axios/instance.ts
  src/apis/auth/authApi.ts
  src/components/inquiry/InquiryItem.tsx
  src/hooks/queries/useDuplicateCheck.ts
  src/hooks/queries/useGetInquiry.ts
  src/hooks/queries/useGetKeywordArtWork.ts
  src/hooks/queries/useGetPick.ts
  src/hooks/queries/useGetPickDetail.ts
  src/hooks/queries/useGetProfile.ts
  src/hooks/queries/useGetSellingArtWork.ts
  src/pages/auth/id.tsx
  src/pages/auth/kakao/callback.tsx
  src/pages/auth/login.tsx
  src/pages/auth/naver/callback.tsx
  src/pages/auth/password.tsx
  src/pages/profile/inquiry.tsx
  src/pages/profile/register/index.tsx
  src/pages/profile/security/index.tsx
  src/pages/profile/security/password.tsx
  src/utils/localStorage/token/index.ts
  yarn.lock
Labels: BugFix, Feature

#196 1 : 1 문의 수정 API 연결
  src/apis/auth/authApi.ts
  src/components/inquiry/InquiryItem.tsx
  src/pages/profile/inquiry.tsx
  src/utils/formatBytes.ts
Labels: Feature, fix

#197 react query hook type 적용 및 state 제거
  src/@types/index.d.ts
  src/apis/_axios/instance.ts
  src/apis/auth/authApi.ts
  src/hooks/mutation/useLoginMutation.ts
  src/hooks/queries/useGetProfile.ts
  src/pages/auth/login.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/keyword.tsx
Labels: Feature

#202 채팅 페이지 주석 제거
  src/pages/chat/index.tsx
Labels: fix

#205 레이아웃 안 맞는 부분 수정
  src/components/common/Layout.tsx
  src/components/common/Tab.tsx
  src/pages/_app.tsx
  src/pages/home/index.tsx
Labels: fix

#201 문의 등록 후 폼 clear
  src/pages/profile/inquiry.tsx
Labels: fix

#206 채팅방 목록 조회 훅 & API 구현
  src/apis/chat/chatApi.ts
  src/apis/chat/socketConnect.js
  src/hooks/queries/chat/useGetChatRoom.ts
  src/pages/chat/index.tsx
Labels: feature

#208 remote image에 next/image 사용
  next.config.js
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
Labels: feature, refactor

#214 디자인 수정(반응형으로)
  src/components/common/Layout.tsx
  src/components/common/Tab.tsx
  src/pages/_app.tsx
  src/pages/begin.tsx
Labels: fix

#212 달력 특정 달 주차 짤림 현상 수정
  src/components/home/Calendar.tsx
Labels: fix

#217 회원가입 약관 동의 수정
  public/svg/icons/icon_arrow_down.svg
  src/features/user/userSlice.ts
  src/pages/auth/join01.tsx
  src/pages/profile/register/index.tsx
Labels: feature, fix

#216 무한 API 전송 해결
  src/apis/_axios/instance.ts
  src/components/common/Button.tsx
  src/hooks/queries/useGetProfile.ts
  src/pages/auth/login.tsx
Labels: bug

#223 작품 상세 조회, 찜하기/취소하기 API 구현
  src/apis/_axios/instance.ts
  src/apis/artwork/artworkApi.ts
  src/components/common/Navigate.tsx
  src/components/home/ExhibitionItem.tsx
  src/hooks/queries/useGetDetail.ts
  src/pages/begin.tsx
  src/pages/detail.tsx
  src/pages/detail/[id].tsx
  src/pages/home/index.tsx
  src/pages/home/view.tsx
Labels: feature

#222 폰트 적용 및 작품등록 버튼 고정
  src/components/home/FloatButton.tsx
  src/pages/home/index.tsx
Labels: fix

#225 refresh 무한 요청 에러 해결
  src/apis/_axios/instance.ts
Labels: bug

#228 키워드 수정 구현 및 컴포넌트 리팩토링
  src/apis/auth/authApi.ts
  src/apis/profile/profileApi.ts
  src/apis/profile/profileApi.type.ts
  src/components/common/Button.tsx
  src/components/profile/Selectkeyword.tsx
  src/hooks/mutations/useJoinMuation.ts
  src/hooks/mutations/useKeywordMutation.ts
  src/hooks/mutations/useLoginMutation.ts
  src/pages/auth/join01.tsx
  src/pages/auth/join02.tsx
  src/pages/auth/join03.tsx
  src/pages/auth/join04.tsx
  src/pages/auth/login.tsx
  src/pages/profile/keyword.tsx
  src/stories/Button.tsx
  src/utils/keywordList.ts
Labels: feature, refactor

#229 폰트 전역 공급 및 탭 채팅 아이콘 변경
  public/svg/icons/Tab/icon_chat.svg
  public/svg/icons/Tab/icon_chat_focus.svg
  src/pages/_app.tsx
Labels: fix

#232 홈에서 커스터마이징 작품목록 불러올때 랜더링 실패하는 오류 해결
  src/apis/home/homeApi.ts
  src/apis/home/homeApi.type.ts
  src/hooks/queries/useGetCustomizedArtWork.ts
  src/hooks/queries/useGetKeywordArtWork.ts
  src/pages/home/index.tsx
Labels: fix

#234 전시작품 전체보기 페이지 무한스크롤 구현
  src/apis/home/homeApi.ts
  src/hooks/queries/useGetCustomizedArtWork.ts
  src/hooks/queries/useGetInfiniteArtWork.ts
  src/pages/home/index.tsx
  src/pages/home/view.tsx
Labels: feature, fix

#233 채팅 - connect, subscribe 구현
  src/@types/index.d.ts
  src/apis/chat/chatApi.ts
  src/apis/chat/chatApi.type.ts
  src/apis/chat/socketConnect.js
  src/apis/profile/profileApi.ts
  src/components/chat/ChatMessage.tsx
  src/components/chat/ChatRoom.tsx
  src/components/profile/WishCard.tsx
  src/hooks/queries/chat/useGetChatRoom.ts
  src/hooks/queries/chat/useGetChatRoomList.ts
  src/hooks/queries/profile/useGetWish.ts
  src/pages/chat/[id].tsx
  src/pages/chat/index.tsx
  src/pages/detail/[id].tsx
  src/pages/profile/wish.tsx
Labels: feature

#236 디자인 수정 반영(auth페이지)
  public/svg/example/example_artwork_1.svg
  public/svg/example/example_artwork_2.svg
  public/svg/example/example_artwork_3.svg
  public/svg/example/example_artwork_4.svg
  public/svg/example/example_artwork_5.svg
  public/svg/example/example_artwork_6.svg
  public/svg/example/example_artwork_7.svg
  public/svg/example/example_artwork_8.svg
  public/svg/example/example_artwork_9.svg
  public/svg/icons/icon_clock_brand.svg
  public/svg/icons/icon_clock_hand.svg
  public/svg/icons/icon_logo_main.svg
  src/@types/index.d.ts
  src/components/auction/AuctionNavigate.tsx
  src/components/common/Button.tsx
  src/components/common/KeywordBox.tsx
  src/components/common/Navigate.tsx
  src/components/exhibition/Modal.tsx
  src/components/home/AuctionItem.tsx
  src/components/home/ScheduleItem.tsx
  src/components/profile/Selectkeyword.tsx
  src/pages/auction/index.tsx
  src/pages/auth/id.tsx
  src/pages/auth/join01.tsx
  src/pages/auth/join02.tsx
  src/pages/auth/join03.tsx
  src/pages/auth/join04.tsx
  src/pages/auth/login.tsx
  src/pages/auth/password.tsx
  src/pages/begin.tsx
  src/pages/detail/[id].tsx
  src/pages/exhibition/index.tsx
  src/pages/home/index.tsx
  src/pages/search.tsx
Labels: refactor

#239 작가등록 후 완료페이지로 이동
  public/image/congratulations.png
  src/apis/profile/profileApi.ts
  src/apis/profile/profileApi.type.ts
  src/hooks/mutations/useRoleMutation.ts
  src/pages/profile/register/complete.tsx
  src/pages/profile/register/index.tsx
Labels: fix

#238 알림 API 구현
  public/svg/icons/notice/icon_notice_bid.svg
  public/svg/icons/notice/icon_notice_bid_fail.svg
  public/svg/icons/notice/icon_notice_bid_success.svg
  public/svg/icons/notice/icon_notice_chat.svg
  public/svg/icons/notice/icon_notice_inquiry.svg
  public/svg/icons/notice/icon_notice_post.svg
  public/svg/icons/notice/icon_notice_post_auction.svg
  public/svg/icons/notice/icon_notice_post_exhibition.svg
  src/apis/profile/profileApi.ts
  src/apis/profile/profileApi.type.ts
  src/components/notice/NoticeItem.tsx
  src/hooks/queries/useGetNotice.ts
  src/pages/notice.tsx
Labels: feature

#246 전시회 페이지 디자인 수정
  src/components/exhibition/Modal.tsx
  src/pages/exhibition/index.tsx
Labels: fix

#249 중복 체크 커스텀 훅 사용하여 구현
  src/@types/auth.d.ts
  src/apis/auth/authApi.ts
  src/apis/profile/profileApi.ts
  src/hooks/queries/useDuplicateCheck.ts
  src/hooks/queries/useGetDuplicateCheck.ts
  src/pages/auth/join02.tsx
  src/pages/profile/edit.tsx
Labels: refactor
