Repository Att-ies/frontend, pull requests merged in 2023-02, with the labels that each got.

#252 interval 함수 & 카운트다운 훅 생성
  src/hooks/useCountDown.ts
  src/hooks/useInterval.ts
Labels: feature

#251 경매목록 페이지 구현
  src/@types/auction.d.ts
  src/apis/auction/auctionApi.ts
  src/components/auction/ArtWorkItem.tsx
  src/components/auction/Timer.tsx
  src/hooks/queries/auction/useGetNowAuctionArtworkList.ts
  src/hooks/useCountDown.ts
  src/pages/auction/index.tsx
  src/utils/priceToString.ts
  src/utils/secondToDate.ts
Labels: feature

#256 회원가입 약관 모달 구현
  src/components/auth/Modal.tsx
  src/components/common/Button.tsx
  src/pages/auth/join01.tsx
Labels: feature

#259 경매 상세 페이지 구현
  public/svg/icons/auction/icon_arrow_black.svg
  public/svg/icons/auction/icon_arrow_white.svg
  public/svg/icons/auction/icon_heart_black.svg
  public/svg/icons/auction/icon_heart_white.svg
  src/components/home/ExhibitionItem.tsx
  src/pages/auction/[id].tsx
  src/pages/auction/index.tsx
  src/pages/detail/[id].tsx
  tailwind.config.js
Labels: feature

#264 작품 찜하기 취소하기 낙관적 업데이트로 구현
  public/svg/icons/auction/icon_auction_gray.svg
  public/svg/icons/icon_clock_white.svg
  src/@types/artwork.d.ts
  src/apis/artwork/artworkApi.ts
  src/components/auction/ArtWorkItem.tsx
  src/hooks/mutations/useDeletePrefer.ts
  src/hooks/mutations/usePostPrefer.ts
  src/hooks/queries/useGetDetail.ts
  src/pages/_app.tsx
  src/pages/auction/[id].tsx
  src/pages/auction/index.tsx
Labels: feature

#267 exhibition 타입 네이밍 수정
  src/@types/exhibition.d.ts
  src/components/exhibition/AuctionItem.tsx
  src/hooks/queries/useGetExhibition.ts
Labels: fix

#270 경매 응찰하기 구현
  src/@types/auction.d.ts
  src/apis/auction/auctionApi.ts
  src/components/auction/AskPriceModal.tsx
  src/hooks/mutations/usePutBidding.ts
  src/hooks/queries/auction/useGetBiddingHistory.ts
  src/hooks/queries/useGetDetail.ts
  src/hooks/useCountDown.ts
  src/pages/auction/[id].tsx
  src/pages/auction/bidding/[id].tsx
  src/pages/auction/detail.tsx
  src/pages/auction/index.tsx
  src/utils/leastAskPrice.ts
Labels: feature

#273 전시회 API 수정에 따른 모달 수정
  src/@types/exhibition.d.ts
  src/components/exhibition/Modal.tsx
  src/pages/exhibition/[id].tsx
  src/pages/exhibition/view.tsx
  src/pages/home/view.tsx
  src/pages/profile/[id].tsx
Labels: fix

#297 검색 페이지 기능 구현
  public/svg/icons/icon_checked_brand.svg
  src/@types/search.d.ts
  src/apis/artwork/artworkApi.ts
  src/components/search/FilterDropdown.tsx
  src/components/search/RecentSearchBox.tsx
  src/components/search/SearchItem.tsx
  src/hooks/mutations/useDeleteWord.ts
  src/hooks/queries/useGetSearchArtWork.ts
  src/pages/search.tsx
Labels: feature

#311 문의 페이지 훅 생성 & 낙관적 업데이트 & 디자인 수정
  src/@types/profie.d.ts
  src/@types/profile.d.ts
  src/apis/profile/profileApi.ts
  src/components/inquiry/InquiryItem.tsx
  src/hooks/mutations/useDeleteInquiry.ts
  src/hooks/mutations/usePatchInquiry.ts
  src/hooks/mutations/usePostInquiry.ts
  src/hooks/queries/useGetInquiry.ts
  src/pages/profile/inquiry.tsx
Labels: ✨ Feature

#314 알림페이지 낙관적 업데이트 구현
  src/components/notice/NoticeItem.tsx
  src/hooks/mutations/useDeleteNotice.ts
  src/pages/notice.tsx
Labels: 📌 QA

#312 소셜 로그인 버튼 임시로 제거
  src/pages/auth/login.tsx
Labels: 📌 QA

#313 모바일 layout issue 해결
  src/components/common/Tab.tsx
Labels: 📌 QA

#317 알림 페이지 텍스트, 버튼 겹침 수정
  src/components/notice/NoticeItem.tsx
Labels: 📌 QA

#316 작품등록 버튼 fixed로 레이아웃 수정
  src/components/home/FloatButton.tsx
Labels: 📌 QA

#318 알림페이지 디자인 수정
  src/components/notice/NoticeItem.tsx
Labels: 📌 QA

#322 경매 관련 작은 오류 수정
  src/components/exhibition/Modal.tsx
  src/pages/auction/index.tsx
Labels: 📌 QA

#323 로그인 페이지 디자인 수정
  src/pages/auth/join01.tsx
  src/pages/auth/join02.tsx
  src/pages/auth/join03.tsx
  src/pages/auth/login.tsx
  src/utils/keywordList.ts
Labels: 📌 QA

#324 activity 패딩 조절
  src/components/profile/Activity.tsx
Labels: 📌 QA

#326 동적 라우팅
  src/components/chat/ChatRoom.tsx
  src/components/exhibition/Modal.tsx
  src/components/home/ExhibitionItem.tsx
  src/components/profile/pick/PickArtist.tsx
  src/components/search/SearchItem.tsx
  src/pages/auction/bidding.tsx
  src/pages/auction/view.tsx
  src/pages/chat/room.tsx
  src/pages/exhibition/detail.tsx
  src/pages/home/index.tsx
  src/pages/profile/detail.tsx
Labels: 📌 QA

#327 찜작품 이미지 비율 수정
  src/components/profile/WishCard.tsx
Labels: 📌 QA

#329 관리자 페이지 추가구현 : 지난 경매 리스트 불러오기 & 1대1문의 답변 기능 추가
  src/apis/admin/admin.ts
  src/components/admin/PastAuctionList.tsx
  src/hooks/queries/admin/useGetAsk.ts
  src/pages/admin.tsx
Labels: ✨ Feature

#332 Meta Tag 추가
  src/components/HeadMeta.tsx
  src/pages/_app.tsx
  src/pages/home/index.tsx
Labels: ✨ Feature

#331 구글 애널리틱스 구현
  config.ts
  src/pages/_app.tsx
  src/pages/auth/login.tsx
  src/utils/gtag.js
Labels: ✨ Feature

#334 홈화면 전시작품 겹침 수정 & home/view 레이아웃 수정
  src/apis/profile/profileApi.type.ts
  src/components/common/NoticeIcon.tsx
  src/components/home/ExhibitionItem.tsx
  src/pages/home/index.tsx
  src/pages/home/view.tsx
Labels: 📌 QA

#335 검색페이지 작품 크기 반응형 & Grid 정렬
  src/components/search/SearchItem.tsx
  src/pages/search.tsx
Labels: 📌 QA

#337 리스트 없을 시 화면 구현
  public/svg/none/bid.svg
  public/svg/none/chat.svg
  public/svg/none/notice.svg
  public/svg/none/pick.svg
  public/svg/none/selling.svg
  public/svg/none/wish.svg
  src/components/common/None.tsx
  src/components/profile/pick/PickArtist.tsx
  src/hooks/queries/artwork/useGetMyArtWork.ts
  src/pages/chat/index.tsx
  src/pages/notice.tsx
  src/pages/profile/bid.tsx
  src/pages/profile/pick.tsx
  src/pages/profile/selling.tsx
  src/pages/profile/wish.tsx
Labels: ✨ Feature, 📌 QA

#336 작품 보증서 서명이 아닌 작품보증서 사진을 서버로 전송
  .yarn/cache/html-to-image-npm-1.11.11-faab8eba97-b453beca72.zip
  package.json
  public/svg/post/logo_small.svg
  src/hooks/mutations/usePostArtwork.ts
  src/pages/auction/view.tsx
  src/pages/home/post.tsx
  src/utils/today.ts
  yarn.lock
Labels: ✨ Feature, 📌 QA

#339 문의 페이지 디자인 수정 & 문의 등록 훅 수정
  src/components/inquiry/InquiryItem.tsx
  src/hooks/mutations/usePostInquiry.ts
  src/pages/profile/inquiry.tsx
Labels: 📌 QA

#341 리팩토링 (QA수정사항 반영, 오류 수정)
  src/@types/auction.d.ts
  src/components/GoogleScript.tsx
  src/components/MetaHead.tsx
  src/components/common/KeywordBox.tsx
  src/components/notice/NoticeItem.tsx
  src/hooks/mutations/usePostArtwork.ts
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/auction/bidding.tsx
  src/pages/auction/view.tsx
  src/pages/begin.tsx
  src/pages/home/index.tsx
  src/pages/home/post.tsx
  src/pages/profile/index.tsx
  src/pages/profile/inquiry.tsx
  src/pages/profile/keyword.tsx
Labels: 🐞 Bug, ✨ Feature, 📌 QA

#343 응찰페이지 작품 사진 보여주기
  src/@types/auction.d.ts
  src/pages/auction/bidding.tsx
Labels: 📌 QA

#344 프로필 사진 통합
  src/components/exhibition/Modal.tsx
  src/pages/auction/view.tsx
  src/pages/profile/detail.tsx
  src/pages/profile/index.tsx
Labels: 📌 QA

#345 리팩토링 (QA수정사항 반영, 오류 수정)
  src/apis/chat/socketConnect.js
  src/components/chat/ChatRoom.tsx
  src/components/common/NoticeIcon.tsx
  src/hooks/mutations/usePatchMember.ts
  src/hooks/mutations/usePatchRegister.ts
  src/hooks/mutations/usePostArtwork.ts
  src/pages/auction/view.tsx
  src/pages/home/index.tsx
  src/pages/profile/detail.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/register/complete.tsx
  src/pages/profile/register/index.tsx
  src/pages/search.tsx
Labels: 🐞 Bug, ✨ Feature, 📌 QA

#347 홈화면 네비게이션 바 추가 & 경매 컴포넌트 수정
  src/components/exhibition/GenreModal.tsx
  src/components/home/ScheduleItem.tsx
  src/pages/home/index.tsx
Labels: 📌 QA

#352 모달 위치 수정 & 윈도우 사이즈 훅 생성
  src/components/exhibition/Modal.tsx
  src/hooks/useWindowSize.ts
  src/pages/exhibition/view.tsx
Labels: ✨ Feature, 📌 QA

#356 온보딩, 로그인 화면 버튼 위로 올리기
  src/pages/auth/login.tsx
  src/pages/begin.tsx
Labels: 🧑‍🎨 Style, 📌 QA

#359 전시회 모달 수정
  src/components/exhibition/Modal.tsx
  src/pages/exhibition/detail.tsx
Labels: 🔨 Refactor

#360 반응형 모달 위치 수정
  src/components/exhibition/Modal.tsx
  src/pages/exhibition/detail.tsx
  src/pages/exhibition/view.tsx
Labels: 🔨 Refactor

#365 hotfix : 토스트 안 뜸 현상
  src/pages/profile/edit.tsx
Labels: 🐞 Bug

#366 fix : 채팅방 안들어가지는 오류 해결
  src/pages/chat/room.tsx
Labels: 🐞 Bug

#367 fix : 옆 칸 짤림 현상 해결
  src/pages/auction/view.tsx
Labels: 🐞 Bug
